# Generated by Django 5.0.6 on 2025-11-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingplan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hostingplan',
            name='backup_limit',
        ),
        migrations.RemoveField(
            model_name='hostingplan',
            name='database_limit',
        ),
        migrations.RemoveField(
            model_name='hostingplan',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='hostingplan',
            name='ports',
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='swap',
            field=models.IntegerField(default=0, help_text='Swap in MB'),
        ),
        migrations.AlterField(
            model_name='hostingplan',
            name='docker_image',
            field=models.CharField(help_text='Docker image for the server', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hosting_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.hostingplan'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
