# Generated by Django 5.0.6 on 2026-01-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hosting_plan',
        ),
        migrations.RemoveField(
            model_name='pendingorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pendingorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='HostingPlan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='PendingOrder',
        ),
    ]
